#define COLOUR_FG_TITLE 0xFFEB
#define COLOUR_FG_SECONDARY 0x371E
#define COLOUR_FG_PRIMARY TFT_WHITE
#define COLOUR_BG_PRIMARY_SELECTED 0xB3F
#define COLOUR_BG_MENU_SELECTED 0x84FC
#define COLOUR_BG_PRIMARY TFT_BLACK
